version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: youcode-evaluator-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - youcode-network
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: youcode-evaluator-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: youcode_evaluator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - youcode-network

  nginx:
    image: nginx:alpine
    container_name: youcode-evaluator-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - youcode-network
    depends_on:
      - app

networks:
  youcode-network:
    driver: bridge

volumes:
  postgres_data:
