version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: youcode-quiz
    container_name: youcode-quiz-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - youcode-quiz

  db:
    image: mysql:8.0
    container_name: youcode-quiz-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - youcode-quiz

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: youcode-quiz-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - youcode-quiz

  nginx:
    image: nginx:alpine
    container_name: youcode-quiz-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - youcode-quiz

networks:
  youcode-quiz:
    driver: bridge

volumes:
  mysql_data:
